version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5352:8080"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - USERNAME=respina
      - EMAIL=respina@gmail.com
      - PASSWORD=respina123

